=== doliroj929/Validaci-n_json_xml/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="precio" type="xs:decimal"/>
                            <xs:element name="stock" type="xs:integer"/>
                            <xs:element name="categoria" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== doliroj929/Validaci-n_json_xml/productos.xml
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="esquema.xsd">
    <producto>
        <nombre>camiseta</nombre>
        <precio>2</precio>
        <stock>15</stock>
        <categoria>ropa</categoria>
    </producto>
    <producto>
        <nombre>1984</nombre>
        <precio>"2"</precio>
        <stock>15</stock>
        <categoria>libros</categoria>
    </producto>
    <producto>
        <nombre>ram</nombre>
        <precio>2</precio>
        <stock>15</stock>
        <categoria>informatica</categoria>
    </producto>
</productos>
